#!/usr/bin/env node
/**
 * Fetch project card thumbnails from the old Notion portfolio.
 *
 *   npm run fetch-covers
 *
 * These are Notion *page covers*, and they are the one thing the Markdown
 * export leaves out entirely — so unlike everything else in `public/media/`,
 * their source of record is the live public site, not the Drive export. Several
 * (the CFD contour plot, the glider photo, the CSWA results screen) exist
 * nowhere else.
 *
 * Because that source could disappear, the optimised WebP output is committed.
 * This script exists so the step is reproducible and documented, not because it
 * needs to run again.
 *
 * Output: public/media/<slug>/cover.webp + src/data/cover-manifest.js
 */
import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import { PROJECTS } from "../src/data/content.js";

const run = promisify(execFile);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const SITE = "https://alecstanley.notion.site";
const COLLECTION_ID = "303fd0db-9845-81bb-bb2e-000b4c562a02";
const VIEW_ID = "303fd0db-9845-81f4-bc18-000cb6d21d5b";

/* Cards render ~370px wide at 168px tall; 900px covers 2× displays with room
   to spare. */
const COVER_WIDTH = 900;
const COVER_QUALITY = 80;

/** Notion titles differ from ours by dashes and spacing, so match on a fold. */
const fold = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

async function queryCollection() {
  const res = await fetch(`${SITE}/api/v3/queryCollection`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "User-Agent": "Mozilla/5.0" },
    body: JSON.stringify({
      collectionId: COLLECTION_ID,
      collectionViewId: VIEW_ID,
      loader: {
        type: "reducer",
        reducers: { collection_group_results: { type: "results", limit: 200 } },
        searchQuery: "",
        userTimeZone: "Australia/Melbourne",
      },
      query: {},
    }),
  });
  if (!res.ok) throw new Error(`queryCollection: HTTP ${res.status}`);
  return res.json();
}

function coversFrom(payload) {
  const out = [];
  for (const [id, record] of Object.entries(payload.recordMap?.block ?? {})) {
    const value = record.value?.value ?? record.value ?? {};
    const cover = value.format?.page_cover;
    if (!cover) continue;
    const title = (value.properties?.title ?? [])
      .map((run) => run[0])
      .join("")
      .trim();
    if (!title) continue;
    const src = cover.startsWith("http") ? cover : `${SITE}/image/${encodeURIComponent(cover)}`;
    out.push({ id, title, url: `${src}?table=block&id=${id}&cache=v2&width=1600` });
  }
  return out;
}

const byTitle = new Map(PROJECTS.map((p) => [fold(p.title), p]));
const covers = coversFrom(await queryCollection());

const manifest = {};
const problems = [];
let bytesIn = 0;
let bytesOut = 0;

for (const cover of covers) {
  const project = byTitle.get(fold(cover.title));
  // The root page has a cover too; only project rows matter.
  if (!project) continue;

  const res = await fetch(cover.url, { headers: { "User-Agent": "Mozilla/5.0" } });
  if (!res.ok) {
    problems.push(`  MISS  ${project.id} ${cover.title}: HTTP ${res.status}`);
    continue;
  }
  const buf = Buffer.from(await res.arrayBuffer());
  bytesIn += buf.length;

  const tmp = path.join(os.tmpdir(), `cover-${process.pid}-${project.slug}`);
  await fs.writeFile(tmp, buf);

  const outDir = path.join(ROOT, "public", "media", project.slug);
  await fs.mkdir(outDir, { recursive: true });
  const out = path.join(outDir, "cover.webp");

  const { stdout } = await run("sips", ["-g", "pixelWidth", "-g", "pixelHeight", tmp]);
  const w = Number(stdout.match(/pixelWidth:\s*(\d+)/)?.[1] ?? 0);
  const h = Number(stdout.match(/pixelHeight:\s*(\d+)/)?.[1] ?? 0);

  await run("cwebp", [
    "-quiet",
    "-q",
    String(COVER_QUALITY),
    "-m",
    "6",
    ...(w > COVER_WIDTH ? ["-resize", String(COVER_WIDTH), "0"] : []),
    tmp,
    "-o",
    out,
  ]);
  await fs.rm(tmp, { force: true });

  const scale = w > COVER_WIDTH ? COVER_WIDTH / w : 1;
  manifest[project.slug] = {
    path: path.relative(path.join(ROOT, "public"), out),
    w: Math.round(w * scale),
    h: Math.round(h * scale),
  };
  bytesOut += (await fs.stat(out)).size;
  process.stdout.write(`  ${project.id}  ${cover.title.slice(0, 48)}\n`);
}

await fs.writeFile(
  path.join(ROOT, "src", "data", "cover-manifest.js"),
  `// GENERATED by scripts/fetch-covers.mjs — do not edit by hand.\n` +
    `// Project card thumbnails, sourced from the old Notion site's page covers.\n` +
    `// The Markdown export does not include these; see the script for why.\n` +
    `export default ${JSON.stringify(manifest, null, 2)};\n`,
);

const missing = PROJECTS.filter((p) => !manifest[p.slug]);
console.log(
  `\n${Object.keys(manifest).length}/${PROJECTS.length} covers — ` +
    `${(bytesIn / 1048576).toFixed(1)} MB in -> ${(bytesOut / 1048576).toFixed(1)} MB out`,
);
if (missing.length) problems.push(`  MISS  no cover matched: ${missing.map((p) => p.id).join(", ")}`);
if (problems.length) {
  console.error(`\n${problems.join("\n")}`);
  process.exit(1);
}
